# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [20.x, 22.x]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Prepare ${{ matrix.node-version }}
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.2.1
      - run: npx playwright install
      - uses: actions/checkout@v4
      - name: Setup ${{ matrix.node-version }}
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.2.1
      - run: pnpm install --frozen-lockfile
      - run: npm run build
      - run: npm test
      - run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
